POST http://localhost:4000/api/v1/signup/verify
Content-Type: application/json

{
  "email": "mrsrjn224@gmail.com",
  "password": "StrongPassword123",
  "name": "New Client",
  "location": "City Name",
  "phone": 9825958298,
  "gender":"M",
  "otp" : 234567
}